export const SOCKET_EVENTS = {
  // Character related events
  CHARACTER: {
    SELECT: 'CHARACTER_SELECT',
    SELECT_SUCCESS: 'CHARACTER_SELECT_SUCCESS',
    SELECT_ERROR: 'CHARACTER_SELECT_ERROR',
  },
  // Game related events
  GAME: {
    START: 'GAME_START',
    START_SUCCESS: 'GAME_START_SUCCESS',
    START_ERROR: 'GAME_START_ERROR',
  },
  // Prologue related events
  PROLOGUE: {
    PROLOGUE_INITIALIZED: 'PROLOGUE_INITIALIZED',
    UPDATE_PROLOGUE_PROGRESS: 'UPDATE_PROLOGUE_PROGRESS',
    COMPLETE_PROLOGUE: 'COMPLETE_PROLOGUE',
  },
} as const;
